server:
  port: 8082
  error:
    path: /error
  servlet:
    context-path: /api

spring:
  application:
    name: quiz_ad_app
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_ad
    hikari:
      username: local
      password: local
      maximum-pool-size: 100
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 50000
        connection:
          autocommit: true
#        show_sql: true
        format_sql: true
        highlight_sql: ture
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      default:
        host: 127.0.0.1
        port: 6379
        database: 2

  mvc:
    converters:
      preferred-json-mapper: jackson
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

  web:
    resources:
      chain:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
#  cloud:
#    config:
#      enabled: false
#      name: mk-service

#  config:
#    import: "optional:configserver:https://github.com/youngma/local-config"

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "refresh"

logging:
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      clean-history-on-start: true

  charset:
    file: UTF-8
    console: UTF-8

  level:
    root: info
    test: debug
    web: debug
    com:
      ads:
        main: debug
    org:
      hibernate:
        stat: trace
        SQL: debug
        orm:
#          results:
#            loading:
#              entity: debug
          jdbc:
            bind: trace
app:
  app-server: http://localhost:8082/api
  file-server: http://localhost:9000
  file:
    uploadTempPath: /Users/bob/projects/file-upload/temp
    uploadPath: /Users/bob/projects/file-upload/files

  quiz:
    join-key:
      user: USER_QUIZ_JOIN
      daily: DAILY_QUIZ_JOIN
      total: TOTAL_QUIZ_JOIN
    lock-key: QUIZ_LOCK

